{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-external
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-data-plane.componentLabels" (dict "context" . "component" "gateway") | nindent 4 }}
spec:
  gatewayClassName: openchoreo
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: gateway-external
  listeners:
    - name: http
      protocol: HTTP
      port: {{ .Values.gateway.config.envoyGateway.gateway.httpPort | default 80 }}
      allowedRoutes:
        namespaces:
          from: All
{{- if .Capabilities.APIVersions.Has "cert-manager.io/v1" }}
    - name: https
      protocol: HTTPS
      port: {{ .Values.gateway.config.envoyGateway.gateway.httpsPort | default 443 }}
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: openchoreo-gateway-tls
            namespace: {{ .Release.Namespace }}
{{- end }}

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: gateway-external
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-data-plane.componentLabels" (dict "context" . "component" "gateway") | nindent 4 }}
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        name: gateway-external
      envoyService:
        name: gateway-external
{{- end }}
