apiVersion: v2
name: openchoreo-data-plane
description: A Helm chart for OpenChoreo Data Plane
type: application

# Version strategy: latest-dev for development, replaced by CI for releases
version: 0.0.0-latest-dev
appVersion: "latest-dev"

home: https://github.com/openchoreo/openchoreo
icon: https://openchoreo.dev/img/openchoreo-logo.svg
sources:
  - https://github.com/openchoreo/openchoreo
keywords:
  - openchoreo
  - internal-developer-platform
  - idp
  - kubernetes
  - developer-experience
  - devops
  - platform-engineering
  - data-plane
  - gateway
  - observability
maintainers:
  - name: OpenChoreo Team
    url: https://github.com/openchoreo/openchoreo
dependencies:
  - name: external-secrets
    version: 0.19.2
    repository: "https://charts.external-secrets.io"
    condition: external-secrets.enabled
  - name: gateway-helm
    repository: "oci://docker.io/envoyproxy"
    version: v1.5.4
    condition: gateway.enabled
  - name: cert-manager
    repository: oci://quay.io/jetstack/charts
    condition: cert-manager.enabled
    version: "v1.16.2"
