{{- if and (index .Values "external-secrets" "enabled") .Values.fakeSecretStore.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-wait-rolebinding
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "openchoreo-build-plane.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: eso-wait-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: eso-wait-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
